// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchProjectMemberships(arg1) {
  return window['go']['main']['App']['FetchProjectMemberships'](arg1);
}

export function FetchRedmineProjects() {
  return window['go']['main']['App']['FetchRedmineProjects']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
