// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function FetchRedmineProjects():Promise<Array<models.Project>>;

export function Greet(arg1:string):Promise<string>;
